### ISSUE TITLE
you have no idea how this works do you?

### ISSUE THREAD

**Issue by opendata26** [KaeruTeam/android_kernel_nx#1]
for android you can use current kernel with something like https://github.com/robherring/generic_device or write a new dts for l4t, what you are currently trying to do is stupid.

**Comment by JoshuaDoes** [comment]
I'd like to ask that issues made for any of our repositories be written with a calmer and more informative mindset.

We understand that these current repositories aren't 100% on track, as we also are just a bunch of curious (for the most part) teenagers looking to experiment and learn with Linux, Android, and the Nintendo Switch by attempting to port the aftermarket Android custom firmware LineageOS to the Nintendo Switch. Our first attempt was to upstream the kernel to 4.16-rc1 and then apply fail0verflow's Nintendo Switch patches and continue from there (which is representative of our current public repositories), however we have since taken a different approach in private that has shown even further progress (SurfaceFlinger is currently able to clear the screen before crashing due to SELinux).

We aren't claiming to know exactly what we are doing, this is merely a project that we're hoping to eventually get working. We're using various sources from working Tegra X1 devices such as the Pixel C (the original base of these repositories) and the Nvidia Shield Android TV (the closest in hardware to the Nintendo Switch as far as we can tell).

**Comment by opendata26** [comment]
@JoshuaDoes , yeah sorry for being a bit rude, as for your sufaceflinger issue just disable selibux, (androidboot.selinux=permissive) in cmdline

**Comment by JoshuaDoes** [comment]
@opendata26 It's all good, and sadly we've already tried that to no avail

**Comment by opendata26** [comment]
@JoshuaDoes Could you send a logcat and dmesg, I might be able to have a quick look at it, if that didn't fix it selinux definitely isn't the issue. Also, may I ask you are porting android, is it the Odin DTS from l4t ?

**Comment by JoshuaDoes** [comment]
I'm sadly not doing the testing, but when available I'll get them for you. And I haven't yet touched L4T, we've been experimenting with other things already setup for Android that uses the Tegra X1

**Comment by JoshuaDoes** [comment]
I'm sadly not doing the testing, but when available I'll get them for you. And I haven't yet touched L4T, we've been experimenting with other things already setup for Android that uses the Tegra X1

**Comment by opendata26** [comment]
@JoshuaDoes thanks, by l4t I mean shield stock kernel for android, just revert https://github.com/antmicro/nvidia-linux-3.10/commit/531033a083ba87e3216f428c4a1bc02f2f19a66c and apply patch in https://imgur.com/a/JRrFIMN image, this should work with shield TV android trees pretty easily

**Comment by JoshuaDoes** [comment]
@opendata26 Is there a method to contact you? Discord is preferred, as it's what we're currently using for communication and collaboration on our projects

**Comment by opendata26** [comment]
@joshuadoes sorry, don't have discord, is IRC or hangouts okay?

**Comment by JoshuaDoes** [comment]
@opendata26 It might go better over IRC tbh, but haven't touched it in some time sadly

**Comment by opendata26** [comment]
@JoshuaDoes got discord nick is opendata#2571

**Comment by randompasser** [comment]
Have you tried asking on XDA? I have yet to see anyone talking about Linux on Switch over there, maybe you will someone who is able to help.
